import express from 'express';
import { getAllShippings, createShipping, updateShipping, getAllFinishedGoods } from '../controllers/shippingController.js';
import { authMiddleware } from '../middleware/authMiddleware.js';
const router = express.Router();
router.use(authMiddleware);
router.get('/finished-goods', getAllFinishedGoods);
router.get('/', getAllShippings);
router.post('/', createShipping);
router.put('/:id', updateShipping);
export default router;